### ISSUE TITLE
Persist Store Form Data

### ISSUE THREAD

**Issue by BatemanVO** [aggiewb/salmon-cookies#43]
Pat would like the information he enters on his table - either via existing functionality to add new rows or, once #42 is completed, editing an existing one - to remain between page refreshes. He doesn't want to pay for a database and he doesn't care about sharing the information with anyone else, so he's fine if it only stores in his local browser. The important part is having the data be persistent in some fashion.

Refactor the store form to cache all data in the table via `localStorage`. Additionally, add functionality to recalculate store totals and update the `localStorage` cache - the store names should not change and any new stores should not be lost, only the hourly and daily totals should be recalculated.

**Comment by aggiewb** [comment]
#50
