### ISSUE TITLE
Replace object literals with constructor function

### ISSUE THREAD

**Issue by BatemanVO** [aggiewb/salmon-cookies#5]
Per the first part of requirements from [this lab assignment](https://github.com/codefellows/amazon-201d1/tree/master/class-07-object-constructors-html-tables/lab), all object literals in code should be replaced by a constructor function.

Additionally, the `randomCustomersPerHour` method should be added to the constructor function's `prototype`, instead of being declared within the constructor function.

Doing so will help make the code scale better and be easier to maintain, as well as making it more reusable by creating constructor functions that are possibly reusable in other contexts.

**Comment by BatemanVO** [comment]
QA/UAT complete, marking as ready for deployment.

**Comment by aggiewb** [comment]
@BatemanVO Developer post deploy verification

**Comment by BatemanVO** [comment]
PM post-deploy verification complete.
